"""Render scan results as a table, as JSON or as Markdown."""

from __future__ import annotations

import json
import os
import sys
from typing import TextIO

from .catalog import App
from .checks import DISABLED, ENABLED, UNKNOWN
from .scanner import MANUAL, NOT_INSTALLED, PARTIAL, Result, summarize

LABELS = {
    PARTIAL: "PARTIAL",
    ENABLED: "ON",
    DISABLED: "OFF",
    UNKNOWN: "UNKNOWN",
    MANUAL: "MANUAL",
    NOT_INSTALLED: "ABSENT",
}

COLORS = {
    PARTIAL: "\033[33m",
    ENABLED: "\033[31m",
    DISABLED: "\033[32m",
    UNKNOWN: "\033[33m",
    MANUAL: "\033[35m",
    NOT_INSTALLED: "\033[90m",
}
BOLD = "\033[1m"
DIM = "\033[90m"
RESET = "\033[0m"


def use_color(stream: TextIO) -> bool:
    if os.environ.get("NO_COLOR"):
        return False
    if os.environ.get("FORCE_COLOR"):
        return True
    return hasattr(stream, "isatty") and stream.isatty()


class Painter:
    def __init__(self, enabled: bool) -> None:
        self.enabled = enabled

    def status(self, status: str) -> str:
        text = LABELS[status]
        return f"{COLORS[status]}{text}{RESET}" if self.enabled else text

    def bold(self, text: str) -> str:
        return f"{BOLD}{text}{RESET}" if self.enabled else text

    def dim(self, text: str) -> str:
        return f"{DIM}{text}{RESET}" if self.enabled else text


def _plain_width(text: str) -> int:
    out, skip = 0, False
    for char in text:
        if char == "\033":
            skip = True
        elif skip:
            if char == "m":
                skip = False
        else:
            out += 1
    return out


def _pad(text: str, width: int) -> str:
    return text + " " * max(0, width - _plain_width(text))


def render_table(results: list[Result], painter: Painter, verbose: bool = False) -> str:
    if not results:
        return "No application from the catalog was found on this machine.\n"

    rows = [
        (painter.status(r.status), r.app.name, f"{r.app.category} · {r.app.verification}", r.reason)
        for r in results
    ]
    status_w = max(_plain_width(r[0]) for r in rows)
    name_w = min(38, max(len(r[1]) for r in rows))

    lines = []
    for (status, name, category, reason), result in zip(rows, results):
        line = f"{_pad(status, status_w)}  {_pad(name, name_w)}  {painter.dim(category)}"
        if reason:
            line += f"\n{' ' * (status_w + 2)}{painter.dim(reason)}"
        lines.append(line)
        if verbose:
            lines.append(f"{' ' * (status_w + 2)}{painter.dim('· ' + provenance(result.app))}")
            # One setting can serve several components; show it once.
            for source, evidence in dict.fromkeys((f.source, f.evidence) for f in result.findings):
                lines.append(f"{' ' * (status_w + 2)}{painter.dim('· ' + source + ': ' + evidence)}")
    return "\n".join(lines) + "\n"


def provenance(app: App) -> str:
    """One line: verification, audit date, scope and version range."""
    text = f"{app.verification}, audited {app.verified_at or 'never'}; scope: {', '.join(app.scope)}"
    if app.version_note:
        text += f"; versions: {app.version_note}"
    return text


def render_summary(results: list[Result], painter: Painter) -> str:
    counts = summarize(results)
    parts = [
        f"{counts[ENABLED]} on",
        f"{counts[DISABLED]} off",
        f"{counts[PARTIAL]} partial",
        f"{counts[UNKNOWN]} unknown",
        f"{counts[MANUAL]} manual",
    ]
    if counts[NOT_INSTALLED]:
        parts.append(f"{counts[NOT_INSTALLED]} absent")
    head = painter.bold(f"{counts['total']} applications scanned: ")
    return head + ", ".join(parts) + "\n"


def render_fixes(results: list[Result], painter: Painter) -> str:
    todo = [r for r in results if r.needs_action]
    if not todo:
        return painter.bold("No actionable findings in the scanned catalog entries.\n")
    lines = [painter.bold("How to turn the telemetry off:"), ""]
    for result in todo:
        app = result.app
        lines.append(f"{painter.status(result.status)} {painter.bold(app.name)}  ({app.id})")
        lines.append(f"    {app.what}")
        for step in app.steps:
            lines.append(f"    - {step}")
        if app.env:
            pairs = " ".join(f"{k}={v}" for k, v in app.env.items())
            lines.append(f"    - export {pairs}")
        if app.docs:
            lines.append(f"    {painter.dim(app.docs)}")
        lines.append("")
    return "\n".join(lines)


def render_shell_profile(results: list[Result]) -> str:
    """Print the export lines that switch the telemetry off."""
    lines = ["# Generated by telescan. Add to your shell profile.", ""]
    seen: dict[str, str] = {}
    for result in results:
        if not result.needs_action:
            continue
        for key, value in result.app.env.items():
            if key not in seen:
                seen[key] = value
                lines.append(f"export {key}={value}  # {result.app.name}")
    if len(lines) == 2:
        lines.append("# Nothing to export.")
    return "\n".join(lines) + "\n"


def render_commands(results: list[Result]) -> str:
    lines = ["# Generated by telescan. Review before you run any of these.", ""]
    for result in results:
        if not result.needs_action:
            continue
        for command in result.app.commands:
            lines.append(f"{command}  # {result.app.name}")
    if len(lines) == 2:
        lines.append("# No command to run.")
    return "\n".join(lines) + "\n"


def render_json(results: list[Result]) -> str:
    payload = {
        "summary": summarize(results),
        "results": [
            {
                "id": r.app.id,
                "name": r.app.name,
                "category": r.app.category,
                "installed": r.installed,
                "status": r.status,
                "reason": r.reason,
                "what": r.app.what,
                "docs": r.app.docs,
                "verification": r.app.verification,
                "verified_at": r.app.verified_at,
                "scope": r.app.scope,
                "versions": r.app.version_note,
                "evidence": r.app.evidence,
                "version": r.version,
                "findings": [
                    {
                        "state": f.state,
                        "evidence": f.evidence,
                        "source": f.source,
                        "component": f.component,
                        "profile": f.profile,
                    }
                    for f in r.findings
                ],
                "components": [
                    {"name": c.name, "status": c.status, "reason": c.reason, "profile": c.profile}
                    for c in r.components
                ],
                "disable": {
                    "steps": r.app.steps,
                    "commands": r.app.commands,
                    "env": r.app.env,
                },
            }
            for r in results
        ],
    }
    return json.dumps(payload, indent=2) + "\n"


def render_markdown(results: list[Result]) -> str:
    counts = summarize(results)
    lines = [
        "# Telemetry report",
        "",
        f"{counts['total']} applications scanned: {counts[ENABLED]} on, {counts[DISABLED]} off, "
        f"{counts[PARTIAL]} partial, {counts[UNKNOWN]} unknown, {counts[MANUAL]} manual.",
        "",
        "| Status | Application | Category | Verification | Scope | Detail | Docs |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in results:
        reason = r.reason.replace("|", "\\|")
        docs = f"[docs]({r.app.docs})" if r.app.docs else ""
        verification = f"{r.app.verification} ({r.app.verified_at})"
        scope = ", ".join(r.app.scope)
        if r.app.version_note:
            scope += f"; versions: {r.app.version_note}"
        lines.append(
            f"| {LABELS[r.status]} | {r.app.name} | {r.app.category} | {verification} | {scope} "
            f"| {reason} | {docs} |"
        )
    lines.append("")
    return "\n".join(lines) + "\n"


def render_app_details(app: App, painter: Painter) -> str:
    lines = [
        painter.bold(f"{app.name}  ({app.id})"),
        f"  category   {app.category}",
        f"  platforms  {', '.join(app.platforms)}",
        f"  default    telemetry is {app.default_state} out of the box",
        f"  what       {app.what}",
        f"  scope      {', '.join(app.scope)}",
        f"  verified   {app.verification} ({app.verified_at or 'never'})",
    ]
    if app.version_note:
        lines.append(f"  versions   {app.version_note}")
    lines += [
        "",
        painter.bold("  How to turn it off:"),
    ]
    for step in app.steps:
        lines.append(f"    - {step}")
    if app.env:
        for key, value in app.env.items():
            lines.append(f"    - export {key}={value}")
    if app.docs:
        lines += ["", f"  docs       {app.docs}"]
    for url in app.evidence:
        lines.append(f"  evidence   {url}")
    lines.append("")
    return "\n".join(lines)


def write(text: str, stream: TextIO | None = None) -> None:
    # Resolved at call time so that tests (and pipes) can replace sys.stdout.
    (stream or sys.stdout).write(text)
